version: '3.7'

services:
  frontend:
    container_name: mentee-frontend
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  backend:
    container_name: mentee-backend
    build: ./backend
    ports:
      - '8000:8000'
    env_file:
    - ./backend/.env