version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  backend-format:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          command: |
            cd backend
            pip install -r requirements-dev.txt --user
            /home/circleci/.local/bin/black . --check 
  frontend-format:
    docker:
      - image: cimg/node:16.19.0
    steps:
      - checkout
      - run:
          command: |
            cd frontend
            yarn
            yarn format:check

workflows:
  main:
    jobs:
      - backend-format
      - frontend-format
