export const LANGUAGES = [
  "Hindu",
  "Urdu",
  "Spanish",
  "Arabic",
  "French",
  "German",
  "English",
  "Russian",
  "Swahili",
  "Mandarin",
  "Cantonese",
  "Bengali",
  "Japanese",
  "Italian",
  "Portuguese",
];

export const SPECIALIZATIONS = [
  "Advocacy and Activism",
  "Arts: Design/Music/Dance and More",
  "Citizenship",
  "Education, Personal Guidance On Next Steps",
  "Entrepreneurship",
  "Finance, Business",
  "Finance, Personal",
  "Health, Community and Environment",
  "Health, Personal: Nutrition, Personal Life Coach, Yoga & Meditation",
  "Interview Skills & Practice",
  "Journalism",
  "Language Lessons",
  "Letter Writing and Other Communications",
  "Legal Issues, Business",
  "Legal Issues, Related to Personal Issues (Excluding Citizenship)",
  "Media/Public Relations",
  "Medicine",
  "Nonprofits/NGOs",
  "Professional Speaking",
  "Resume Writing",
  "Self Confidence",
  "Small Businesses",
  "Technology Training",
  "Other",
];
