# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Run yarn build
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - working-directory: ./frontend
      - run: yarn install
      - run: yarn run build

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "MENTEE-h4i"
          heroku_email: "h4i.mentee.auth@gmail.com"
