name: New Backend Tests

on:
  pull_request:
    branches:
      - dev
      
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      MONGO_HOST: ${{ secrets.MONGO_HOST }}
      MONGO_DB: ${{ secrets.MONGO_DB }}
      FIREBASE_SERVICE_KEY: ${{ secrets.FIREBASE_SERVICE_KEY }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      IMGUR_KEY: ${{ secrets.IMGUR_KEY }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_PHONE: ${{ secrets.TWILIO_PHONE }}
      FLASK_APP: ${{ secrets.FLASK_APP }}

      BASE_URL: ${{ secrets.BASE_URL }}
      TEST_MENTOR_EMAIL: ${{ secrets.TEST_MENTOR_EMAIL }}
      TEST_MENTOR_PASSWORD: ${{ secrets.TEST_MENTOR_PASSWORD }}
      TEST_MENTOR_PHONE_NUMBER: ${{ secrets.TEST_MENTOR_PHONE_NUMBER }}
      TEST_MENTEE_EMAIL: ${{ secrets.TEST_MENTEE_EMAIL }}
      TEST_MENTEE_PASSWORD: ${{ secrets.TEST_MENTEE_PASSWORD }}
      TEST_MENTEE_PHONE_NUMBER: ${{ secrets.TEST_MENTEE_PHONE_NUMBER }}
      TEST_PARTNER_EMAIL: ${{ secrets.TEST_PARTNER_EMAIL }}
      TEST_PARTNER_PASSWORD: ${{ secrets.TEST_PARTNER_PASSWORD }}
      TEST_GUEST_EMAIL: ${{ secrets.TEST_GUEST_EMAIL }}
      TEST_GUEST_PASSWORD: ${{ secrets.TEST_GUEST_PASSWORD }}
      TEST_ADMIN_EMAIL: ${{ secrets.TEST_ADMIN_EMAIL }}
      TEST_ADMIN_PASSWORD: ${{ secrets.TEST_ADMIN_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
    
      - name: Install Poetry
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install poetry
          pip install lockfile
    
      - name: Build and run Backend
        run: |
          . .venv/bin/activate
          cd backend
          touch firebase_service_key.json
          echo "$FIREBASE_SERVICE_KEY" > firebase_service_key.json
          cp firebase_service_key.json ./tests
          ls
          cat firebase_service_key.json
          poetry install
          poetry run start &

      - name: Check if Flask server is up
        run: |
          retries=100
          until curl -sSf http://localhost:8000/api/translation; do
            ((retries--)) || exit 1
            sleep 1
          done
    
      - name: Run Tests
        run: |
          . .venv/bin/activate
          cd backend
          cd tests
          pytest